// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadTasks() {
  return window['go']['main']['App']['LoadTasks']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTasks(arg1) {
  return window['go']['main']['App']['SaveTasks'](arg1);
}

export function SelectAppFile() {
  return window['go']['main']['App']['SelectAppFile']();
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}
