// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOS():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadSettings():Promise<main.Config>;

export function LoadTasks():Promise<Array<main.Task>>;

export function OpenBrowser(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Config):Promise<string>;

export function SaveTasks(arg1:Array<main.Task>):Promise<string>;

export function SelectAppFile():Promise<string>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;
